name: Release

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - ubuntu:latest
          - boky/postfix:v3.4.0
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: kahirokunn
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image
        run: docker pull ${{ matrix.image }}
      - name: Tag image
        run: docker tag ${{ matrix.image }} ghcr.io/kahirokunn/public-image-puller/${{ matrix.image }}
      - name: Push image to GitHub Container Registry
        run: docker push ghcr.io/kahirokunn/public-image-puller/${{ matrix.image }}
